name: Address

on: [pull_request_target, issues, fork]

jobs:
  address:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Thanks for reporting the issue. We will look over the issue as soon as possible."
        pr-message: "Thanks for your contribution. We will consider your request and make needful changes."
